// MARK: ASCII Art Lookup

/// Provides name-based lookup functionality for Pokemon ASCII art.
extension AsciiPokemonArt {
    
    /// Dictionary links names to their corresponding ASCII artwork.
    static let namArtDict: [String: String] = [
        "Bulbasaur": bulbasaur,
        "Ivysaur": ivysaur,
        "Venusaur": venusaur,
        "Charmander": charmander,
        "Charmeleon": charmeleon,
        "Charizard": charizard,
        "Squirtle": squirtle,
        "Wartortle": wartortle,
        "Blastoise": blastoise,
        "Caterpie": caterpie,
        "Metapod": metapod,
        "Butterfree": butterfree,
        "Weedle": weedle,
        "Kakuna": kakuna,
        "Beedrill": beedrill,
        "Pidgey": pidgey,
        "Pidgeotto": pidgeotto,
        "Pidgeot": pidgeot,
        "Rattata": rattata,
        "Raticate": raticate,
        "Spearow": spearow,
        "Fearow": fearow,
        "Ekans": ekans,
        "Arbok": arbok,
        "Pikachu": pikachu,
        "Raichu": raichu,
        "Sandshrew": sandshrew,
        "Sandslash": sandslash,
        "Nidoran♀": nidoranF,
        "Nidorina": nidorina,
        "Nidoqueen": nidoqueen,
        "Nidoran♂": nidoranM,
        "Nidorino": nidorino,
        "Nidoking": nidoking,
        "Clefairy": clefairy,
        "Clefable": clefable,
        "Vulpix": vulpix,
        "Ninetales": ninetales,
        "Jigglypuff": jigglypuff,
        "Wigglytuff": wigglytuff,
        "Zubat": zubat,
        "Golbat": golbat,
        "Oddish": oddish,
        "Gloom": gloom,
        "Vileplume": vileplume,
        "Paras": paras,
        "Parasect": parasect,
        "Venonat": venonat,
        "Venomoth": venomoth,
        "Diglett": diglett,
        "Dugtrio": dugtrio,
        "Meowth": meowth,
        "Persian": persian,
        "Psyduck": psyduck,
        "Golduck": golduck,
        "Mankey": mankey,
        "Primeape": primeape,
        "Growlithe": growlithe,
        "Arcanine": arcanine,
        "Poliwag": poliwag,
        "Poliwhirl": poliwhirl,
        "Poliwrath": poliwrath,
        "Abra": abra,
        "Kadabra": kadabra,
        "Alakazam": alakazam,
        "Machop": machop,
        "Machoke": machoke,
        "Machamp": machamp,
        "Bellsprout": bellsprout,
        "Weepinbell": weepinbell,
        "Victreebel": victreebel,
        "Tentacool": tentacool,
        "Tentacruel": tentacruel,
        "Geodude": geodude,
        "Graveler": graveler,
        "Golem": golem,
        "Ponyta": ponyta,
        "Rapidash": rapidash,
        "Slowpoke": slowpoke,
        "Slowbro": slowbro,
        "Magnemite": magnemite,
        "Magneton": magneton,
        "Farfetch’d": farfetchd,
        "Doduo": doduo,
        "Dodrio": dodrio,
        "Seel": seel,
        "Dewgong": dewgong,
        "Grimer": grimer,
        "Muk": muk,
        "Shellder": shellder,
        "Cloyster": cloyster,
        "Gastly": gastly,
        "Haunter": haunter,
        "Gengar": gengar,
        "Onix": onix,
        "Drowzee": drowzee,
        "Hypno": hypno,
        "Krabby": krabby,
        "Kingler": kingler,
        "Voltorb": voltorb,
        "Electrode": electrode,
        "Exeggcute": exeggcute,
        "Exeggutor": exeggutor,
        "Cubone": cubone,
        "Marowak": marowak,
        "Hitmonlee": hitmonlee,
        "Hitmonchan": hitmonchan,
        "Lickitung": lickitung,
        "Koffing": koffing,
        "Weezing": weezing,
        "Rhyhorn": rhyhorn,
        "Rhydon": rhydon,
        "Chansey": chansey,
        "Tangela": tangela,
        "Kangaskhan": kangaskhan,
        "Horsea": horsea,
        "Seadra": seadra,
        "Goldeen": goldeen,
        "Seaking": seaking,
        "Staryu": staryu,
        "Starmie": starmie,
        "Mr. Mime": mrMime,
        "Scyther": scyther,
        "Jynx": jynx,
        "Electabuzz": electabuzz,
        "Magmar": magmar,
        "Pinsir": pinsir,
        "Tauros": tauros,
        "Magikarp": magikarp,
        "Gyarados": gyarados,
        "Lapras": lapras,
        "Ditto": ditto,
        "Eevee": eevee,
        "Vaporeon": vaporeon,
        "Jolteon": jolteon,
        "Flareon": flareon,
        "Porygon": porygon,
        "Omanyte": omanyte,
        "Omastar": omastar,
        "Kabuto": kabuto,
        "Kabutops": kabutops,
        "Aerodactyl": aerodactyl,
        "Snorlax": snorlax,
        "Articuno": articuno,
        "Zapdos": zapdos,
        "Moltres": moltres,
        "Dratini": dratini,
        "Dragonair": dragonair,
        "Dragonite": dragonite,
        "Mewtwo": mewtwo,
        "Mew": mew
    ]
    
    /// Returns the ASCII art for a given Pokemon name.
    ///
    /// - Parameter name: The display name (e.g. "Pikachu", "Mr. Mime").
    /// - Returns: The matching ASCII art, or a fallback message if not found.
    static func showArt(for name: String) -> String {
        return namArtDict[name] ?? "ASCII Art for \(name) not found."
    }
    
}
